apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: {{.Values.namespace | default "nginx-web"}}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx
    spec:
        containers:
        - name: nginx
          image: nginx:{{ .Values.nginxVersion | default "1.25-alpine" }}
          ports:
          - containerPort: 80
              name: http
          resources:
              {{ toYaml .Values.resources }}
          volumeMounts:
          - name: nginx-config
              mountPath: /etc/nginx/conf.d
              subPath: default.conf
          livenessProbe:
              httpGet:
              path: /
              port: http
              initialDelaySeconds: 3
              periodSeconds: 5
        volumes:
        - name: nginx-config
          configMap:
              name: nginx-config